### ISSUE TITLE
Whole Idea Card component should be clickable

### ISSUE THREAD

**Issue by chadcrotchett** [dev-launchers/dev-launchers-platform#1949] opened 2024-09-06 21:32 UTC
Per #1915, the whole Idea Card component should be clickable to view the idea, including the image and text body, as one rectangle shape.

Mouse-over, hover, and all standard styling shall be confirmed as part of the button as well.

![Image](https://github.com/user-attachments/assets/c895692f-bd21-4e3b-877a-d5f3ba31dd6d)

- [ ] Oct 9 2024 : Limit description to 'first 100 characters'

**Comment by dbradham** [comment] 2024-09-22 16:45
I posted this in Discord, but seeing some styling regressions from this change-
![Image](https://github.com/user-attachments/assets/869a1342-4c59-4227-a59d-772385cbd048)

**Comment by chadcrotchett** [comment] 2024-10-08 03:58
@vivienzhou2014 Thanks for being open to picking this up. Once you are able to get your hands dirty, I'll probably ask what (if any) additional information would have helped you develop a solution quicker/easier.

**Comment by AlinaU1** [comment] 2024-10-17 15:24
Hi @vivienzhou2014,
Thanks for the update. 

There are a few things to consider and check:

1. the gap between the image and the idea title and make it 16px (1 rem) with title height of 28px (1.75 rem)![Image](https://github.com/user-attachments/assets/a4be44c2-1b39-45e6-9be3-2c9c38212ad5)
2. The description has 40px (2.5 rem) height.
3. The title and the description together - 76px height with the gap of 8px between them.
4. Padding of 8px between the image and borders on top, left and right ![Image](https://github.com/user-attachments/assets/bb27579f-a95f-4508-8b1e-1bf71c41bdfc)
5. Card height: 376px for most screens. For screens that are larger than 1440px - card height increases to 408px (if applicable)
6. Card width: the card should be responsive for all devices. If the mobile device is 320px - the card's width is 280px. ![Image](https://github.com/user-attachments/assets/845b68bb-7a60-4bf5-bdaf-25e57e24ee4f)

7. Margins and gutter: 
For screen XL (1280px) - margin: 48px, gutter: 32px; 
For screen 2XL (1536) - margin: 64px, gutter - 32px; 
For screen md (tablet 834px) - margin: 24px, gutter: 24px;
For mobile devices: margin: 20px, gutter: gutter: 20px.

8. The paddings between the cards should be consistent with gaps (e.g. if the vertical padding (gutter) is 32px the horizontal is 32px as well ![Image](https://github.com/user-attachments/assets/1584de92-c9e0-40a6-ab45-ab2efb88c008)

9. For desktop devices - 3 cards in a row, for tablet - 2 cards in a row, for mobile - 1.

**Comment by Ahsaask** [comment] 2024-10-24 17:13
Hi @AlinaU1 @RETprojects ,

It seems the character limit works as expected, but i still tried limiting to it two lines instead of characters. This is the result before and after 

Before:
![Image](https://github.com/user-attachments/assets/5896edd6-fb2b-4b60-b247-78a262137699)

After:
![Image](https://github.com/user-attachments/assets/11126f96-ff80-4d64-bf1b-ad634249fbdd)

Is this the desired result? @AlinaU1 

Thanks!

**Comment by AlinaU1** [comment] 2024-10-25 15:23
Hi @Ahsaask,
Yes, that looks great! And it work on different breakpoints as well?
Thank you!

**Comment by Ahsaask** [comment] 2024-10-25 16:15
> Hi [@Ahsaask](https://github.com/Ahsaask), Yes, that looks great! And it work on different breakpoints as well? Thank you!

Yes! It does. Thanks!

**Comment by RETprojects** [comment] 2024-10-27 15:14
I found an idea whose description takes up 3 lines:![Image](https://github.com/user-attachments/assets/506691ca-092c-46c0-9da6-08a51639df0d)

**Comment by vivienzhou2014** [comment] 2024-10-29 03:03
> Hi [@vivienzhou2014](https://github.com/vivienzhou2014), Thanks for the update.
> 
> There are a few things to consider and check:
> 
> 1. the gap between the image and the idea title and make it 16px (1 rem) with title height of 28px (1.75 rem)![Image](https://github.com/user-attachments/assets/a4be44c2-1b39-45e6-9be3-2c9c38212ad5)
> 2. The description has 40px (2.5 rem) height.
>    3 The idea title: font size - 20px, line height - 28px; weight - 700; font style bold
> 3. The title and the description together - 76px height with the gap of 8px between them.
> 4. Padding of 8px between the image and borders on top, left and right ![Image](https://github.com/user-attachments/assets/bb27579f-a95f-4508-8b1e-1bf71c41bdfc)
> 5. Margins, gutter, card width height, responsiveness:
> 
> **Screen 2XL (1536):** 3 cards for a row margin left/right - 184px; gutter (gap between cards horizontal and vertical) - 32px; Card width - dynamic; Card height - 376px; Gap between idea description and "updated" - 32px
> 
> **Screen XL (1280px):** 3 cards for a row margin left/right - 48px; gutter (gap between cards horizontal and vertical) - 32px; Card width - dynamic; Card height - 376px; Gap between idea description and "updated" - 32px
> 
> **Screen lg (1024px):** 3 cards for a row margin left/right - 32px; gutter - 24px; Card width - dynamic; Card height - 376px; Gap between idea description and "updated" - 32px
> 
> **Screen md (768px):** 2 cards for a row; margin - 24px; gutter - 24px; Card width - dynamic; Card height - 376px; Gap between idea description and "updated" - 32px
> 
> **Screen sm 640px:** 1 card for a row; margin - 24px; gutter (only vertical gap) - 24px; Card width - dynamic; Card height - 534px; Gap between idea description and "updated" - 48px
> 
> **Screen 390px:** 1 card for a row; margin - 20px; gutter (only vertical gap) - 20px; Card width - dynamic; Card height - 376px; Gap between idea description and "updated" - 32px
> 
> Figma: https://www.figma.com/design/hEDIHsBZYa6hmK8As5mcjy/%5BDL---IdeaSpace%5D-UX-designs?node-id=12100-17982&m=dev

Check point 1-4 is modified. Please check this demo to see if it works as expected. Check point 5 is huge. Need more help to finish.https://github.com/user-attachments/assets/94aa4fd3-bef8-4bf6-a27c-3a89b4e0f095

**Comment by AlinaU1** [comment] 2024-10-31 00:30
**Breakpoint/screen 1192:**
3 cards for a row; 
margin left/right - 48px;
Gutter (gap between cards horizontal and vertical) - 32px; 
Card width - dynamic; 
Card height - 376px; 
Gap between idea description and "updated" - 32px

**Breakpoint/screen 810:** 
2 cards for a row;
margin left/right - 24px
Gutter (gap between cards horizontal and vertical) - 24px;
Card width - dynamic; 
Card height: 376px;
Gap between idea description and "updated" - 32px

**Comment by vivienzhou2014** [comment] 2024-11-02 21:14
@AlinaU1 Please check if this meets the requirements: https://drive.google.com/file/d/1SA7N40V9XdumgOn43OEu-FNI45YxN4KZ/view?usp=drive_link

**Comment by AlinaU1** [comment] 2024-11-02 21:26
Hi @vivienzhou2014,
Everything looks awesome! Thank you for adapting it for the maximum of screens!  

If we still can change the color of "number of comments and upvotes" to **rgba(41, 88, 117, 1)** that would be great
![Image](https://github.com/user-attachments/assets/8e2112dc-cd60-4840-b086-dcff13cf4edb)

thanks again!

**Comment by vivienzhou2014** [comment] 2024-11-02 22:39
@AlinaU1 Hi Alina, I just changed that. How does it look now? ![Image](https://github.com/user-attachments/assets/fec34010-593f-4b89-8aa7-c939f823a232)

**Comment by AlinaU1** [comment] 2024-11-02 23:05
@vivienzhou2014 thanks!
I just approved the ticket

**Comment by RETprojects** [comment] 2024-11-02 23:15
Awesome! I guess the next step is to deploy this ticket to QA!

**Comment by chadcrotchett** [comment] 2024-11-03 22:41
Code must have been embedded with development/ideaspace already, so I believe it also sent this Card formatting to Staging as well.

**Comment by AlinaU1** [comment] 2024-11-04 01:20
Hi @vivienzhou2014 

Just noticed 2 issues:
1. Card height is different from the original design (it should be 376px for most screens) - documented in the comments above;

2. Left/right margin needs improvement as the cards are not aligned with the dropdown and the back button. Let's make sure that for most **desktop** screen sizes (except 1536 and bigger) the margin is **48px**.

**Comment by vivienzhou2014** [comment] 2024-11-04 02:44
@AlinaU1 Hi Alina, 
1. For the height, I tried to do fix height for 376px and it looks very strange. So I did not do it.
![Image](https://github.com/user-attachments/assets/9dc8baed-362f-4978-84e5-c926e559fdb8)

2. For the margin, I did not add any left or right margin for card wrapper. I tried some places in the code base, and it seems like an alignment issue combined with the dynamic card width. I can create a new branch to fix that. Thanks for catching that.

**Comment by vivienzhou2014** [comment] 2024-11-04 03:20
@AlinaU1 is image height 202px for all screen width? I see in the code base now the image width and height is dynamic.

**Comment by AlinaU1** [comment] 2024-11-04 03:35
in Figma the image is on fill or fit if:

the cards height is fixed (376px);
the content height is 126px with gap of 32px;
card bottom padding is 24px;
top padding is 8 px;
global gap (between image and content is 16px).

If the card's height is fixed to 376, the image's height (fit or fill) is 202px so it should change dynamically  based on the cards's height.

video: https://drive.google.com/file/d/1scoNUvFYpE-MLH0x67o94ckKz2nx-oAQ/view?usp=sharing

**Comment by vivienzhou2014** [comment] 2024-11-04 04:01
@AlinaU1 Thank you for the clarification. My understanding based on the current image behavior is that when the image width and height are dynamic, the height will adjust according to the width of the image to ensure that the image is not distorted, meaning that the aspect ratio between the height and width remains fixed. So it is better to set a fixed height for image if the card height is fixed.
And another thing is, to set the card height for different screen width is simple. But to set image height for different screen size is kinda impossible. Because the image is not directly in side the cardwrapper. it is inside the card. I do not know how to do that. @RETprojects @Ahsaask Please let me know if you have any idea of how to do that. So if we do not have a solution for that, can we set the card height 376px for all screen sizes?(so that the image height will be fixed no matter the screen width)

**Comment by AlinaU1** [comment] 2024-11-04 15:09
Let's also make sure that:
1. image has an overlay of **rgba(0, 0, 0, 0.05)** or **#0000000 (5% transparency)**;
2. last updated text style: colour: #494949 or rgba(73, 73, 73, 1); weight: 300; font size 12px;
3. number of comments & number of upvotes text style: colour: rgba(115, 57, 172, 1) or #7339AC; weight: 300; font size 12px.

**Comment by vivienzhou2014** [comment] 2024-11-04 16:48
@AlinaU1 
Thank you for your understanding! I have set the image height to 202px and card height to 376px for all screen width. Maybe we can discuss that in next meeting with Remi and Ahsaas for the dynamic image height issue. And code change is made for requirement 1-3. Please check:
https://drive.google.com/file/d/1ptl2V4JJP2RrQshClq9nDMomdG5tCoCP/view?usp=drive_link

**Comment by AlinaU1** [comment] 2024-11-04 22:00
@vivienzhou2014 Can we also make the following update for breakpoint 1536: 
**Breakpoint 1536px:** 
4 cards for a row;
Margins left/right: 64px
gutter: 32px;
card height: 376px;
![Image](https://github.com/user-attachments/assets/b3aaae4a-568f-4d04-8808-53158fc50654)


Thanks!

**Comment by chadcrotchett** [comment] 2024-11-06 23:30
Tailwind code not working on QA, Database/API unavailable in IdeaSpace Staging; so merged directly to Global Staging. @andyzhu7568 go for it!

**Comment by AlinaU1** [comment] 2024-11-07 12:20
Hi @vivienzhou2014. 

The updates:

remove "updated" from "updated: .. .. ago";
the card's corner radius: 20px;
the corner radius of the image: 14px;
Card height: 344px;
image height: 176px;
idea name text style: font size -18px; weight - 700px; line height 24px;
gap between idea name and description - 6px;
for screens starting from 1440px and bigger - 4 cards for a row;
Screen/breakpoint 1440px: margin - 64px; gutter 32px;
Breakpoint 640: 2 cards for a row.

**Comment by vivienzhou2014** [comment] 2024-11-08 03:05
@AlinaU1 Hi Alina, for this requirement: "Screen/breakpoint 1440px: margin - 64px; gutter 32px;" Previously we have a requirement for screen width from 1192px to 1536px that left and right padding is 48px. So now is it 48px for range 1192-1440 and 64px for 1440-1536 ?

**Comment by AlinaU1** [comment] 2024-11-09 02:20
Hi @vivienzhou2014,
Yes,  it's 48px for range 1192-1440 and 64px for 1440-1536. Thanks! Looks good 👍

but this is what it shows for 1539 in the video, looks like it's more than 64
![Image](https://github.com/user-attachments/assets/8e185729-2aa5-4f9b-951b-49544153937b)


In Figma:
![Image](https://github.com/user-attachments/assets/a569d7a8-a57f-4717-8af2-02b6da98b9ed)

Let me know if I confused something. Thanks again

**Comment by andyzhu7568** [comment] 2024-11-09 03:40
Function passed QA in staging.

**Comment by vivienzhou2014** [comment] 2024-11-09 21:28
@AlinaU1 Hi Alina,

Thank you for pointing out that in the video. I double checked and in 1536px screen width, the padding is 64px. Maybe it is the lagging of screenshit. I took another screenshot slowly narrowing the window and it works fine.
![Image](https://github.com/user-attachments/assets/55d725e3-7e8a-4c9d-a14e-e221799c6812)
https://drive.google.com/file/d/19KP3worlRDfmp6oqOIFDJKTCfE8u54E-/view?usp=sharing

**Closed** 2024-12-13 00:48 UTC
